<a href="https://colab.research.google.com/github/yeesem2002/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
 my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
arr = np.array(my_list)

In [5]:
#One dimentional array
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
#Two dimentional array
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#Third parameter is the step size
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
#5 rows by three columns
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#10 evenly space point from 0 to 5
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
#Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.57166656, 0.84489831, 0.50199172, 0.88325365, 0.85532836])

In [23]:
np.random.rand(5,5)

array([[0.53672564, 0.18324946, 0.27589257, 0.64086328, 0.83805064],
       [0.5370987 , 0.69151412, 0.22300542, 0.10833263, 0.27183333],
       [0.84676529, 0.66553602, 0.386675  , 0.88569815, 0.65262672],
       [0.97092382, 0.57441314, 0.72255282, 0.91925869, 0.46258313],
       [0.25367922, 0.30803203, 0.79048037, 0.69018484, 0.61615197]])

In [ ]:
np.random.rand()