<a href="https://colab.research.google.com/github/yeesem/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **List vs np.array**

In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [4]:
for e in L:
  print(e)

1
2
3


In [5]:
for e in A:
  print(e)

1
2
3


In [6]:
L.append(4)

In [8]:
L

[1, 2, 3, 4]

In [9]:
L + [5]

[1, 2, 3, 4, 5]

In [10]:
A + 4

array([5, 6, 7])

In [12]:
A

array([1, 2, 3])

In [13]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [14]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
L2 = []
for e in L:
  L2.append(e+3)

In [16]:
L2

[4, 5, 6, 7]

In [18]:
L2 = [e+3 for e in L]
L2

[4, 5, 6, 7]

In [19]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [20]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [21]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

# **The Dot Product**

In [23]:
a = np.array([1,2])
b = np.array([3,4])

In [24]:
dot = 0
for e,f in zip(a,b):
  dot += e*f
dot

11

In [25]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [26]:
a * b

array([3, 8])

In [27]:
np.sum(a * b)

11

In [28]:
(a * b).sum()

11

In [29]:
np.dot(a,b)

11

In [30]:
a.dot(b)

11

In [31]:
a @ b

11

In [32]:
amag = np.sqrt((a ** 2).sum())
amag

2.23606797749979

# **Speed Test**

In [38]:
from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a,b):
  result = 0
  for e,f in zip(a,b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a,b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 : ",dt1)
print("dt2 : ",dt2)
print("dt1 / dt2: ",dt1.total_seconds()/dt2.total_seconds())

dt1 :  0:00:04.252680
dt2 :  0:00:00.093472
dt1 / dt2:  45.49683327627525


# **Matrices**