<a href="https://colab.research.google.com/github/yeesem/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **List vs np.array**

In [2]:
import numpy as np

In [ ]:
L = [1,2,3]

In [ ]:
A = np.array([1,2,3])

In [ ]:
for e in L:
  print(e)

1
2
3


In [ ]:
for e in A:
  print(e)

1
2
3


In [ ]:
L.append(4)

In [ ]:
L

[1, 2, 3, 4]

In [ ]:
L + [5]

[1, 2, 3, 4, 5]

In [ ]:
A + 4

array([5, 6, 7])

In [ ]:
A

array([1, 2, 3])

In [ ]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L2 = []
for e in L:
  L2.append(e+3)

In [ ]:
L2

[4, 5, 6, 7]

In [ ]:
L2 = [e+3 for e in L]
L2

[4, 5, 6, 7]

In [ ]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

# **The Dot Product**

In [ ]:
a = np.array([1,2])
b = np.array([3,4])

In [ ]:
dot = 0
for e,f in zip(a,b):
  dot += e*f
dot

11

In [ ]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [ ]:
a * b

array([3, 8])

In [ ]:
np.sum(a * b)

11

In [ ]:
(a * b).sum()

11

In [ ]:
np.dot(a,b)

11

In [ ]:
a.dot(b)

11

In [ ]:
a @ b

11

In [ ]:
amag = np.sqrt((a ** 2).sum())
amag

2.23606797749979

# **Speed Test**

In [ ]:
from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a,b):
  result = 0
  for e,f in zip(a,b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a,b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 : ",dt1)
print("dt2 : ",dt2)
print("dt1 / dt2: ",dt1.total_seconds()/dt2.total_seconds())

dt1 :  0:00:04.252680
dt2 :  0:00:00.093472
dt1 / dt2:  45.49683327627525


In [56]:
#Matrix multiplication
from datetime import datetime

A = np.random.rand(10,10)
B = np.random.rand(10,10)

def matrix_multiply(A, B):
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result

t0 = datetime.now()
matrix_multiply(A,B)
dt1 = datetime.now() - t0

t0 = datetime.now()
A.dot(B)
dt2 = datetime.now() - t0

print("dt1 : ",dt1)
print("dt2 : ",dt2)
print("dt1 / dt2: ",dt1.total_seconds()/dt2.total_seconds())

dt1 :  0:00:00.001529
dt2 :  0:00:00.000186
dt1 / dt2:  8.220430107526882


# **Matrices**

In [ ]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [ ]:
L[0]

[1, 2]

In [ ]:
L[0][1]

2

In [ ]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
A[0][1]

2

In [ ]:
A[0,1]

2

In [ ]:
A[:,0]

array([1, 3])

In [ ]:
#Transpose
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Matric Multiplication
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
np.diag(A)

array([1, 4])

In [ ]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

# **Solving Linear Systems**

In [6]:
# x + y = 2200
# 1.5x + y = 5050
A = np.array([[1,1],[1.5,4]])
B = np.array([2200,5050])

np.linalg.solve(A,B)

array([1500.,  700.])

In [7]:
np.linalg.inv(A).dot(B)

array([1500.,  700.])

# **Generating Data**

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
10 * np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [11]:
#Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.random()

0.7915240850790345

In [14]:
np.random.random((2,3))

array([[0.93297374, 0.12422647, 0.72929136],
       [0.01694322, 0.24837638, 0.1438223 ]])

In [15]:
np.random.randn(2,3)

array([[-0.95945202,  2.45888662,  1.31360271],
       [ 0.92846533,  0.66224685,  0.23605914]])

In [16]:
R = np.random.randn(10000 )

In [17]:
R.mean()

-0.016016740096654367

In [18]:
np.mean(R)

-0.016016740096654367

In [19]:
R.var()

0.9923370277787664

In [20]:
R.std()

0.9961611454873988

In [23]:
R = np.random.randn(10000,3)

In [24]:
R.mean(axis = 0)

array([ 0.00191466, -0.0185873 ,  0.01052639])

In [25]:
R.mean(axis = 1)

array([ 0.23388376,  0.6698743 ,  0.56466579, ...,  0.2493964 ,
       -0.06312985, -0.87654522])

In [26]:
R.mean(axis = 1).shape

(10000,)

In [29]:
#covariance
np.cov(R).shape

(10000, 10000)

In [30]:
np.cov(R.T)

array([[0.99653075, 0.00380979, 0.01812514],
       [0.00380979, 1.01789408, 0.01306672],
       [0.01812514, 0.01306672, 0.9851171 ]])

In [31]:
np.cov(R,rowvar= False)

array([[0.99653075, 0.00380979, 0.01812514],
       [0.00380979, 1.01789408, 0.01306672],
       [0.01812514, 0.01306672, 0.9851171 ]])

In [33]:
#random(min,max,size)
#min - inclusive,max - exclusive
np.random.randint(0,10,size = (3,3))

array([[4, 9, 8],
       [6, 5, 1],
       [0, 9, 9]])

In [49]:
#from 0 - 9
np.random.choice(10,size=(3,3))

array([[3, 1, 6],
       [8, 3, 0],
       [7, 0, 2]])

In [54]:
np.random.randn(3,3)

array([[ 0.36905786, -0.11309481,  0.86076776],
       [ 0.4348252 , -0.69413016, -0.99494007],
       [ 1.24533209, -1.17337396, -0.50277   ]])