<a href="https://colab.research.google.com/github/yeesem2002/Python/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Array**

In [1]:
import numpy as np

In [2]:
 my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
arr = np.array(my_list)

In [5]:
#One dimentional array
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
#Two dimentional array
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#Third parameter is the step size
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
#5 rows by three columns
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#10 evenly space point from 0 to 5
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
#Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.57166656, 0.84489831, 0.50199172, 0.88325365, 0.85532836])

In [23]:
np.random.rand(5,5)

array([[0.53672564, 0.18324946, 0.27589257, 0.64086328, 0.83805064],
       [0.5370987 , 0.69151412, 0.22300542, 0.10833263, 0.27183333],
       [0.84676529, 0.66553602, 0.386675  , 0.88569815, 0.65262672],
       [0.97092382, 0.57441314, 0.72255282, 0.91925869, 0.46258313],
       [0.25367922, 0.30803203, 0.79048037, 0.69018484, 0.61615197]])

In [25]:
#From Random normal distribution
np.random.randn(2)

array([1.01351806, 0.88986985])

In [26]:
np.random.randn(4,4)

array([[ 0.55649557, -0.29606407,  1.23737039, -0.92935867],
       [ 1.25721234, -0.50578193,  0.29244642, -0.45296927],
       [ 0.33325857, -0.67084334, -0.38607564, -0.97857151],
       [-0.31760243,  1.03420387, -0.20448339, -0.14261616]])

In [28]:
#First param - low, Second param - high, Third param - number of random Int
np.random.randint(1,100,10)

array([52, 42, 37, 72, 97, 54, 86,  9,  3, 89])

In [29]:
arr = np.arange(25)

In [30]:
ranarr = np.random.randint(0,15,10)

In [32]:
#Reshape the arr array into 5 by 5 matrix
#Will return error when unable to suit the size
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr

array([ 7,  9,  7, 14,  3,  6,  4,  2, 11,  1])

In [36]:
ranarr.max()

14

In [35]:
ranarr.min()

1

In [39]:
#Return the index location of the max value
ranarr.argmax()

3

In [41]:
#Return the index location of the min value
ranarr.argmin()

9

In [44]:
ranarr.shape

(10,)

In [46]:
ranarr.dtype

dtype('int64')

In [47]:
from numpy.random import randint

In [48]:
randint(2,10)

7

# **NumPy Indexing and Selection**

In [49]:
arr = np.arange(0,11)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr[8]

8

In [52]:
arr[1:5]

array([1, 2, 3, 4])

In [53]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [54]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [55]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [58]:
#Set the first 5 numbers in the array to 100
arr[0:5] = 100

In [59]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [60]:
arr = np.arange(0,11)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
slice_of_array = arr[0:6]

In [63]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [64]:
slice_of_array[:] = 99

In [65]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [66]:
arr_copy = arr.copy()

In [67]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
arr_copy[:] = 100

In [69]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [70]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [72]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [73]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [74]:
arr_2d[0][0]

5

In [75]:
arr_2d[1]

array([20, 25, 30])

In [76]:
arr_2d[2][1] #2 bracket

40

In [77]:
arr_2d[2,1] #1 bracket

40

In [78]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [79]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [81]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [82]:
#Conditional selection
arr = np.arange(1,11)

In [83]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
bool_arr = arr > 5

In [88]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [90]:
#Get the data only true
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [92]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [93]:
arr[arr<3]

array([1, 2])

In [95]:
arr_2d = np.arange(50).reshape(5,10)

In [96]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [97]:
#Get rows 1 and 2 as well as columns 3 and 4
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# **NumPy Operations**

In [98]:
arr = np.arange(0,11)

In [99]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [101]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [102]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [104]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [105]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [106]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [107]:
np.max(arr)

10

In [109]:
np.min(arr)

0

In [110]:
np.log(arr)

<ipython-input-110-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [111]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])