<a href="https://colab.research.google.com/github/yeesem/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **List vs np.array**

In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [4]:
for e in L:
  print(e)

1
2
3


In [5]:
for e in A:
  print(e)

1
2
3


In [6]:
L.append(4)

In [8]:
L

[1, 2, 3, 4]

In [9]:
L + [5]

[1, 2, 3, 4, 5]

In [10]:
A + 4

array([5, 6, 7])

In [12]:
A

array([1, 2, 3])

In [13]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [14]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
L2 = []
for e in L:
  L2.append(e+3)

In [16]:
L2

[4, 5, 6, 7]

In [18]:
L2 = [e+3 for e in L]
L2

[4, 5, 6, 7]

In [19]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [20]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [21]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])